server:
  port: 8502
  servlet:
    context-path: /api

spring:
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  devtools:
#    restart:
#      additional-paths: src/main/java


