server:
  port: 8499
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://192.168.0.198:8848/nacos/
    routes:
      - name: 用户服务
        serviceName: sql-father-user-server
        namespace-id: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
        group-name: DEFAULT_GROUP
        location: /v2/api-docs?group=default
