server:
  port: 8499
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://desktop-wsl-tailscale:8848/nacos/
    routes:
      - name: 用户服务
        serviceName: sql-father-user-server
        namespace-id: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
        group-name: DEFAULT_GROUP
        location: /v2/api-docs?group=default
      - name: SQL服务
        serviceName: sql-father-sql-server
        namespace-id: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
        group-name: DEFAULT_GROUP
        location: /v2/api-docs?group=default
      - name: 字段服务
        serviceName: sql-father-field-server
        namespace-id: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
        group-name: DEFAULT_GROUP
        location: /v2/api-docs?group=default
      - name: 词典服务
        serviceName: sql-father-dict-server
        namespace-id: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
        group-name: DEFAULT_GROUP
        location: /v2/api-docs?group=default
      - name: 举报服务
        serviceName: sql-father-report-server
        namespace-id: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
        group-name: DEFAULT_GROUP
        location: /v2/api-docs?group=default
      - name: 表服务
        serviceName: sql-father-table-server
        namespace-id: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
        group-name: DEFAULT_GROUP
        location: /v2/api-docs?group=default
#    config:
#      server-addr: wsl.tailscale.com:8848
#      namespace: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
#      group: DEFAULT_GROUP
#      file-extension: yml
#      shared-configs:
#        - data-id: share-nacos.yml
#          group: DEFAULT_GROUP
#          refresh: true


