server:
  port: 8500

spring:
  application:
    name: sql-father-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.198:8848
        namespace: fdcaf9ca-2c1a-4657-8eef-c32d7f391d21
        group: DEFAULT_GROUP
        register-enabled: true
    gateway:
      routes:
        - id: user-module # 路由名称，要求唯一，名称任意
          uri: lb://sql-father-user-server   # 转发的地址，lb表示使用负载均衡，应用的名称代表地址
          predicates:  # 路由规则，断言什么请求会被路由
            - Path=/user/** # 只要是访问的这个路径，一律都被路由到上面指定的服务

        - id: knife4j-module
          uri: http://localhost:8499 # knife4j文档地址
          predicates:  # 路由规则，断言什么请求会被路由
            - Path=/**
#            - Path=/doc.html#/**
#            - Path=/doc/**
#          filters:
            # 重写url
#            - RewritePath=/doc/(?<segment>.*), /$\{segment}
#            - RewritePath=/doc(?<segment>.*), /doc.html#$\{segment} # 为什么这个不行？
#            /doc.html#/** 似乎是一个整体不可分割
